---
language: ruby
sudo: false
before_install: gem update --system && gem install bundler
branches:
  only:
    - master
bundler_args: --without development system_tests
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.3.1
  - 2.4.0
