---
language: ruby
sudo: false
cache: bundler
before_install: gem update --system 2.1.11
branches:
  only:
    - master
    - 3.0.0
bundler_args: --without development system_tests
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.4
  - 2.3.1
notifications:
  email:
    - tim@github.com
